**Problem Statement:**

A client’s requirement is, he wants to predict the insurance charges based on
the several parameters. The Client has provided the dataset of the same.
As a data scientist, you must develop a model which will predict the insurance
charges.

>1.) Identify your problem statement
>
>2.) Tell basic info about the dataset (Total number of rows, columns)
>
>3.) Mention the pre-processing method if you’re doing any (like converting
string to number – nominal data)
>
>4.) Develop a good model with r2_score. You can use any machine learning
algorithm; you can create many models. Finally, you have to come up
with final model.
>
>5.) All the research values (r2_score of the models) should be documented.
(You can make tabulation or screenshot of the results.)
>
>6.) Mention your final model, justify why u have chosen the same.
>

### 1.) Identify your problem statement

> Need to predict the **Insurance Charges** based on the given data using the best Machine Learning model.
>
> **Step:1** Machine Learning <---(Both Numerical and Categorical values are present in the dataset)
>
> **Step:2** Supervised <---(Input and Output are clearly mentioned)
>
> **Step:3** Regression <---(Output value will be numerical ('float'))

In [1]:
#importing pandas library for data manipulation
import pandas as pd

In [2]:
#Reading the dataset
df=pd.read_csv("insurance_pre.csv")

In [3]:
#Viewing the dataset
df

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

### 2.) Tell basic info about the dataset (Total number of rows, columns)

In [4]:
#description of the dataset
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [5]:
print("Number of Columns:",df.shape[0])
print("Number of Rows:",df.shape[1])

Number of Columns: 1338
Number of Rows: 6

In [6]:
#Checking any null values in any of the feature
df.isna().any().any()

np.False_

### 3.) Mention the pre-processing method if you’re doing any (like converting string to number – nominal data)

> **Data Pre-processing:**
>
> **Step:1** Converting the nominal data into numerical data
>
> **Step:2** Splitting the Input and Output variables
>
> **Step:3** Using sklearn.model_selection, splitting the dataset into Training and Test set
>

#### Step:1

In [7]:
#'Smoker' & 'Sex' features are Catagorical. For Machine Learning purpose, i am converting those features into numerical variables
df=pd.get_dummies(df,drop_first=True,dtype=int)

In [8]:
df

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [9]:
df.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

#### Step:2

In [10]:
#splitting Input and Output Variables
independent=df[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dependent=df[['charges']]

In [11]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [12]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

#### Step:3

In [13]:
#split into training set and test (70/30 ratio)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 0.3, random_state = 0)

In [14]:
X_train.shape

(936, 5)

In [15]:
X_train

      age     bmi  children  sex_male  smoker_yes
1163   18  28.215         0         0           0
196    39  32.800         0         0           0
438    52  46.750         5         0           0
183    44  26.410         0         0           0
1298   33  27.455         2         1           0
...   ...     ...       ...       ...         ...
763    27  26.030         0         1           0
835    42  35.970         2         1           0
1216   40  25.080         0         1           0
559    19  35.530         0         1           0
684    33  18.500         1         0           0

[936 rows x 5 columns]

In [16]:
X_test.shape

(402, 5)

In [17]:
X_test

      age     bmi  children  sex_male  smoker_yes
578    52  30.200         1         1           0
610    47  29.370         1         0           0
569    48  40.565         2         1           1
1034   61  38.380         0         1           0
198    51  18.050         0         0           0
...   ...     ...       ...       ...         ...
1261   28  37.100         1         1           0
494    21  25.700         4         1           1
97     55  38.280         0         1           0
418    64  39.160         1         1           0
920    62  25.000         0         0           0

[402 rows x 5 columns]

In [18]:
y_train

          charges
1163   2200.83085
196    5649.71500
438   12592.53450
183    7419.47790
1298   5261.46945
...           ...
763    3070.80870
835    7160.33030
1216   5415.66120
559    1646.42970
684    4766.02200

[936 rows x 1 columns]

In [19]:
y_test

          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1261   3277.16100
494   17942.10600
97    10226.28420
418   14418.28040
920   13451.12200

[402 rows x 1 columns]

### 4.) Develop a good model with r2_score. You can use any machine learning algorithm; you can create many models. Finally, you have to come up with final model.

> **Machine Learning Algorithms:**
>
> 1. Multiple Linear Regression
>
> 2. Support Vector Machine
>
> 3. Decision Tree
>
> 4. Random Forest

#### 1. Multiple Linear Regression

In [20]:
#importing LinearRegression from sklearn library
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [21]:
#predicting the X_test with the above model
y_pred=regressor.predict(X_test)

In [22]:
#Model Evaluation
from sklearn.metrics import r2_score
r_score=r2_score(y_pred,y_test)
round(r_score,3)

0.71

r2 score is low, **0.71**.

#### 2. Support Vector Machine

In [23]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [24]:
#importing LinearRegression from sklearn library
from sklearn.svm import SVR
regressor_svm = SVR(kernel='rbf',C=3000)
regressor_svm.fit(X_train, y_train)

C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=3000)

In [25]:
y_pred=regressor_svm.predict(X_test)

In [26]:
#Model Evaluation
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
round(r_score,3)

0.866

> The r2 score is better, **0.866**.

#### 3. Decision Tree

In [27]:
#importing DecisionTreeRegressor from sklearn library
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor(criterion='poisson',splitter='best',random_state=42)
regressor=regressor.fit(X_train,y_train)

In [28]:
y_pred=regressor.predict(X_test)

In [29]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
round(r_score,3)

0.736

#### 4. Random Forest

In [30]:
#importing RandomForestRegressor from sklearn library
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=100,criterion='squared_error',max_features='log2',random_state=42)
regressor.fit(X_train,y_train)

C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(max_features='log2', random_state=42)

In [31]:
y_pred=regressor.predict(X_test)

In [32]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
round(r_score,3)

0.874

> The r2 score is better, **0.874**.

### 6.) Mention your final model, justify why u have chosen the same.

> Random Forest works well. In which, iteration-12 & 21 are giving the same R2 score as **0.874**.
>
> R2 score of **0.874** is a larger value compared to all other models. Since I am selecting this as the best model for deployment.

In [33]:
X_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]],
      shape=(936, 5))

In [34]:
import pickle
filename = 'finalized_RF_model.sav'
pickle.dump(regressor, open(filename, 'wb')) #'pickle.dump' is used to store the finalized model(regressor) in the assigned 'filename'
# 'wb' node ensures the file is written as binary data

In [35]:
#loading the model for checking
loaded_model = pickle.load(open('finalized_RF_model.sav', 'rb')) #'pickle.load' is used to load the finalized model
# 'rb' mode is used for reading the saved file

In [36]:
# SAVE BOTH THE MODEL AND THE SCALER USING PICKLE
with open("rf_model.pkl", "wb") as f:
    pickle.dump(loaded_model, f)

with open("scaler.pkl", "wb") as f:
    pickle.dump(sc, f)

In [37]:
independent.columns

Index(['age', 'bmi', 'children', 'sex_male', 'smoker_yes'], dtype='object')

In [38]:
dependent.columns

Index(['charges'], dtype='object')